# Generated by Django 6.0.1 on 2026-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_rename_data_datamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.IntegerField()),
                ('god_rojdeniya', models.IntegerField(blank=True, null=True)),
                ('podpisani_documenti', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('', '')], default='', max_length=3, null=True)),
                ('pol', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6)),
                ('bil_prostoy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('opit_v_doljnosti', models.FloatField()),
                ('activnost', models.FloatField()),
                ('znak_zodiaka', models.CharField(choices=[('Рыбы', 'Козерог'), ('Козерог', 'Козерог'), ('Близнецы', 'Близнецы'), ('Рак', 'Рак'), ('Телец', 'Телец'), ('Дева', 'Дева'), ('Стрелец', 'Стрелец'), ('Весы', 'Весы'), ('Овен', 'Овен'), ('Водолей', 'Водолей'), ('Лев', 'Лев'), ('Скорпион', 'Скорпион')], default='Скорпион', max_length=8)),
                ('vozrast', models.FloatField()),
                ('ocenka_hr', models.FloatField()),
                ('uroven_oplati', models.FloatField()),
                ('oflain_meropriyatiya', models.FloatField()),
                ('obrazovanie', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PHD', 'PHD')], default='Bachelors', max_length=9)),
                ('telefon', models.FloatField()),
                ('gorod', models.CharField(choices=[('Pune', 'Pune'), ('New Delhi', 'New Delhi'), ('Bangalore', 'Bangalore')], default='Pune', max_length=9)),
                ('razmer', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'XXl')], default='XS', max_length=3)),
                ('zakritie_proekti', models.FloatField()),
                ('god_nayma', models.FloatField()),
                ('kursi', models.FloatField()),
                ('otvet', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('real', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True)),
            ],
        ),
    ]
