# Generated by Django 6.0.1 on 2026-01-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataModel',
        ),
    ]
